### ISSUE TITLE
dismiss Control Center view

### ISSUE THREAD

**Issue by Liorkatz** [a3tweaks/Flipswitch#12]
In lockscreen with passcode after openURLAsAlternateAction or long press on the switch
the view of the control canter needs to Dismiss and its not ( to enter the code ) 
i think you need to use 

-(void)controlCenterWillFinishTransitionOpen:(BOOL)controlCenter withDuration:(double)duration

**Comment by fopina** [comment]
I think you meant to report this for FlipControlCenter, not FlipSwitch, no?

**Comment by rpetrich** [comment]
Implemented in one of the previous FlipControlCenter releases.
