### ISSUE TITLE
quickstart guide

### ISSUE THREAD

**Issue by fopina** [a3tweaks/Flipswitch#20]
I've been looking at http://iphonedevwiki.net/index.php/Flipswitch but there's no "quickstart" guide.

Could something like this be added to the wiki (or FlipSwitch README)?

I've been trying to use it in OSX but having some issues.

Something like:

```
git clone --recursive thisrepo
cp libsubstrate.dylib and libflipswitch.dylib from iPhone to theos/lib (unable to build it in OSX? I couldn't)
export THEOS=full path to theos inside the cloned repo
cd Switches/3G
make
export THEOS_DEVICE_IP=somehostname
make install (this didn't work for me, complaining about building package)
or
scp -rp .theos/obj/3G.bundle root@iphone:/Library/Switches/

and respring
```

I've done this (in a copy of 3G switch - my3G - and updating Info.plist) to check it if FlipControlCenter would show the new toggle in the available ones, but it doesn't...

I'm currently installing toolchain and stuff directly in iPhone to see if it works better there, but some sort of quick instructions (even without explanation) could kickstart people (or provide them with extra info to google if they're not comfortable with the setup) :)

:+1: for the library!

**Comment by joemerlino** [comment]
do you want a 3g toggle?

**Comment by fopina** [comment]
I read through #15 thanks :) I just want to try out the switch dev flow for some dummy switch

**Comment by fopina** [comment]
closing this as I guess it doesn't make sense as an issue
