### ISSUE TITLE
Localization of Flipswitch

### ISSUE THREAD

**Issue by pedro-mendonca** [a3tweaks/Flipswitch#22]
I have FlipSwitch and FlipControlCenter installed on iOS 9.0.2, but my localization files aren't installed by default, I have to install the localization bundles manually. Is this normal?
The language bundles exist in the GitHub repo https://github.com/rpetrich/Localization/tree/master/Flipswitch

Thank you.

**Comment by rpetrich** [comment]
Flipswitch and FlipControlCenter do not support localization.

**Comment by pedro-mendonca** [comment]
Thank you for your anwser, I though it did support localization, as you maintain it in your Localization repository.
Thanks.
