### ISSUE TITLE
Respring switcher causes crash on iOS 9.3

### ISSUE THREAD

**Issue by hirakujira** [a3tweaks/Flipswitch#23]
There's no `_relaunchSpringBoardNow ` method in SpringBoard on iOS 9.3.
https://github.com/a3tweaks/Flipswitch/blob/master/Switches/Respring.x#L22
Should use other method to respring.

**Comment by hirakujira** [comment]
BTW, thanks for adding NightShift toggle and fix rotation toggle bug on iOS 9.3. I've removed my packages on my repo. :)

**Comment by rpetrich** [comment]
Oh, this is an embarrassing oversight. I just fixed this exact problem in Activator 😂
