### ISSUE TITLE
Airplay menu doesn't close

### ISSUE THREAD

**Issue by richiegigabit** [a3tweaks/Flipswitch#25]
When switching AirPlay from the FlipSwitch AirPlay menu does not close when 
press the Done button on the upper right  corner. I have to press the home button to dismiss the screen. What is the ETA for the fix? Thank you in advance.

iPhone6,1-7.1.2: 317406ae2ac61f29411eeef24f37d69a9125a958

**Comment by richiegigabit** [comment]
Issue is occurring with Auxo 2

**Comment by rpetrich** [comment]
This should be reported to the developer of that switch.
