### ISSUE TITLE
Can the Vibration code work on a non-jailbroken device?

### ISSUE THREAD

**Issue by jlubeck** [a3tweaks/Flipswitch#26]
I'm trying to disable vibration on my app and I found your code. It's similar to other pieces of code I found online, but I can't seem to make it work, and I'm wondering it is only meant to work on a jailbroken device. 

I don't care about using private APIs or not, as this is for an internal enterprise app. But I do need it on non-jailbroken devices.

I see that the com.apple.springboard.ring-vibrate.changed notification is being posted. But it doesn't seem to actually CHANGE the setting.

Any input/help is appreciated.

Thanks!

**Comment by rpetrich** [comment]
It's not possible to change the ringer state from outside SpringBoard, unfortunately.
